OIFITSlib: write_fits.c File Reference
write_fits.c File Reference
Implementation of functions to write FITS tables from data structures in memory.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "exchange.h"
#include "fitsio.h"
Functions
char ** make_tform (const char **template, int n, int value)
Make deep copy of array of n strings, substituting value for any initial '?'.
void free_tform (char **tform, int n)
Free array of n strings returned by make_tform().
STATUS write_oi_array (fitsfile *fptr, oi_array array, int extver, STATUS *pStatus)
Write OI_ARRAY fits binary table.
STATUS write_oi_target (fitsfile *fptr, oi_target targets, STATUS *pStatus)
Write OI_TARGET fits binary table.
STATUS write_oi_wavelength (fitsfile *fptr, oi_wavelength wave, int extver, STATUS *pStatus)
Write OI_WAVELENGTH fits binary table.
STATUS write_oi_vis (fitsfile *fptr, oi_vis vis, int extver, STATUS *pStatus)
Write OI_VIS fits binary table.
STATUS write_oi_vis2 (fitsfile *fptr, oi_vis2 vis2, int extver, STATUS *pStatus)
Write OI_VIS2 fits binary table.
STATUS write_oi_t3 (fitsfile *fptr, oi_t3 t3, int extver, STATUS *pStatus)
Write OI_T3 fits binary table.
Variables
int oi_hush_errors = 0
If TRUE, don't report I/O errors to stderr.
Detailed Description
Implementation of functions to write FITS tables from data structures in memory.
Copyright (C) 2007 John Young
This file is part of OIFITSlib.
OIFITSlib is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
OIFITSlib is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with OIFITSlib. If not, see http://www.gnu.org/licenses/
Function Documentation
char** make_tform (const char ** template, int n, int value)
Make deep copy of array of n strings, substituting value for any initial '?'.
Referenced by write_oi_t3(), write_oi_vis(), and write_oi_vis2().
void free_tform (char ** tform, int n)
Free array of n strings returned by make_tform().
Referenced by write_oi_t3(), write_oi_vis(), and write_oi_vis2().